services:

  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:8.6.9
    container_name: zeebe
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform

  experiment:
    image: moritz148/measurementsgmt:c8
    container_name: experiment
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPC_ADDRESS=http://zeebe:26500
#      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
#      - ZEEBE_CLIENT_CLOUD_ENABLED=false
      - LOGGING_LEVEL_IO_CAMUNDA_ZEEBE_CLIENT_IMPL=ERROR
      - MY_CUSTOM_VAR=500
    networks:
      - camunda-platform
    depends_on:
      zeebe:
        condition: service_healthy

networks:
  camunda-platform:


