services:
  camundaEngine:
    image: moritz148/measurementsgmt:c7-engine
    container_name: camundaEngine
    restart: unless-stopped
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://db:5432/camunda
      DB_USERNAME: camunda
      DB_PASSWORD: camunda
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1" ]
      interval: 60s
      timeout: 15s
      retries: 5
    depends_on:
      - db
    networks:
      - camunda-platform

  db:
    image: postgres:17
    container_name: postgres-camunda
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: camunda
      POSTGRES_USER: camunda
      POSTGRES_DB: camunda
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - camunda-platform

  experiment:
    container_name: experiment
    image: moritz148/measurementsgmt:c7-benchmark
#    command: /bin/sh
    environment:
      CAMUNDA_ENGINE_URL: http://camundaEngine:8080/engine-rest
      PROCESS_INSTANCES: 100
    restart: "no"
    depends_on:
      camundaEngine:
        condition: service_healthy
    networks:
      - camunda-platform

networks:
  camunda-platform:

#volumes:
#  postgres_data: