name: Camunda 8 Messung - multiple Broker - benchmark
author: Moritz Schwarz <moritz.schwarz@envite.de>
description: usage_scenario for camunda8experiment

compose-file: !include docker-compose-multiple-broker.yaml

services:
  experiment:
    image: moritz148/measurementsgmt:c8-benchmark
    environment:
      - PROCESS_INSTANCES=100
    command: /bin/sh

flow:
  - name: experiment
    container: experiment
    commands:
      - type: console
        command: java -jar demo.jar
        log-stdout: true
#        log-stderr: true