name: Camunda 8 Messung - Single Broker - single
author: Moritz Schwarz <moritz.schwarz@envite.de>
description: usage_scenario for camunda8experiment

compose-file: !include docker-compose-single-broker.yaml

services:
  experiment:
    image: moritz148/measurementsgmt:c8-single
    container_name: experiment
    command: /bin/sh
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPC_ADDRESS=http://zeebe:26500
      #      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      #      - ZEEBE_CLIENT_CLOUD_ENABLED=false
      - LOGGING_LEVEL_IO_CAMUNDA_ZEEBE_CLIENT_IMPL=ERROR
      - PROCESS_INSTANCES=5000
    networks:
      - camunda-platform
    depends_on:
      zeebe:
        condition: service_healthy

flow:
  - name: experiment
    container: experiment
    commands:
      - type: console
        command: java -jar demo.jar
        log-stdout: true
#        log-stderr: true