name: Camunda 8 Messung - multiple Broker - benchmark
author: Moritz Schwarz <moritz.schwarz@envite.de>
description: usage_scenario for camunda8experiment

compose-file: !include docker-compose-c8.8-single-broker.yaml

services:
  experiment:
    #    image: moritz148/measurementsgmt:c8.8-measuring-withresult
    image: moritz148/measurementsgmt:c8.8-measuring
    container_name: experiment
    command: /bin/sh
    environment:
      - GRPC_ADDRESS=http://zeebe-1:26500
      - REST_ADDRESS=http://zeebe-1:8080
      - PROCESS_INSTANCES=1000
      - PROCESS_ID=benchmark
      - LOGGING_LEVEL_APP=info
      - LOGGING_LEVEL_ROOT=off
    networks:
      - camunda
    depends_on:
      zeebe-1:
       condition: service_healthy


flow:
  - name: experiment
    container: experiment
    commands:
      - type: console
        command: java -jar demo.jar
        log-stdout: true
#        log-stderr: true